spring:
  application:
    name: java_labb-webshop
  datasource:
    url: jdbc:mysql://localhost:3306/webshop
    username: root
    password: hej123
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: michaelbergsten@gmail.com
    password: ctsa tasj ruxm bjzd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG

discogs:
  base-url: https://api.discogs.com
  token: TCdgqdBNaMimdlfMJJikcKWvrfDlqFbjtGCosbaj
  endpoints:
    search: /database/search
    release: /releases

